"""Regression coverage for the isolated historical Phase 08 branch.

Phase 08 is deliberately no longer regenerated by the default integrity suite:
it uses the retired quota-based mission policy and its renderer can produce
obsolete artefacts.  The test preserves source and archive traceability without
allowing that branch to run as part of the reference-path verification.
"""
from pathlib import Path

from aquaskim.legacy_registry import legacy_module_names
from aquaskim.paths import DIRECTORIES, PROJECT_ROOT


def test_phase08_is_classified_as_legacy_and_is_not_a_reference_renderer() -> None:
    source = PROJECT_ROOT / "src" / "aquaskim" / "phase08.py"
    text = source.read_text(encoding="utf-8")
    assert "Historical Phase 08 wrapper" in text
    assert "aquaskim.phase08" in legacy_module_names()


def test_historical_phase08_archive_contract_is_retained_when_artifacts_exist() -> None:
    # Existing historical evidence remains readable, but Patch 10.10 does not
    # regenerate it because that could overwrite the reference output portfolio.
    expected = [
        DIRECTORIES["figures"] / "phase08_autonomy_architecture.png",
        DIRECTORIES["tables"] / "phase08_acceptance_checks.csv",
        DIRECTORIES["logs"] / "phase08_visual_quality_manifest.json",
    ]
    existing = [path for path in expected if path.exists()]
    assert all(path.stat().st_size > 0 for path in existing)
