from __future__ import annotations

import json
import zipfile

import pytest

from aquaskim import __version__
from aquaskim.delivery_package import (
    DELIVERY_IDENTIFIER,
    PACKAGE_BASENAME,
    build_final_delivery_package,
    preflight_reproduction_scripts,
)
from aquaskim.paths import DIRECTORIES
from aquaskim.reference_design import load_reference_configuration


def _word_qa_ready() -> bool:
    return (
        (DIRECTORIES["reports"] / "AquaSkim-Sim_Final_Report.docx").exists()
        and (DIRECTORIES["logs"] / "final_word_report_qa.json").exists()
        and (DIRECTORIES["logs"] / "engineering_release_gate.json").exists()
    )


def _delivery_ready() -> bool:
    return (
        (DIRECTORIES["deliverables"] / f"{PACKAGE_BASENAME}.zip").exists()
        and (DIRECTORIES["deliverables"] / "FINAL_DELIVERY_PACKAGE_MANIFEST.json").exists()
        and (DIRECTORIES["deliverables"] / "FINAL_DELIVERY_SHA256SUMS.txt").exists()
    )


def test_delivery_version_contract_matches_reference_design() -> None:
    assert load_reference_configuration().project_version == __version__
    assert __version__.count(".") == 2


def test_delivery_builder_contains_manifest_verification_and_recording_contract() -> None:
    names = set(build_final_delivery_package.__code__.co_names)
    assert {"_delivery_files", "_verify_package", "_audit_markdown", "_record_run"}.issubset(names)
    string_constants = {
        value for value in build_final_delivery_package.__code__.co_consts if isinstance(value, str)
    }
    assert "DELIVERY_PACKAGE_READY" in string_constants


@pytest.mark.skipif(not _word_qa_ready(), reason="Word QA outputs are required before delivery packaging.")
def test_final_delivery_prerequisites_are_available_after_word_qa() -> None:
    assert (DIRECTORIES["reports"] / "AquaSkim-Sim_Final_Report.docx").exists()
    assert (DIRECTORIES["logs"] / "final_word_report_qa.json").exists()
    assert (DIRECTORIES["logs"] / "engineering_release_gate.json").exists()
    qa = json.loads((DIRECTORIES["logs"] / "final_word_report_qa.json").read_text(encoding="utf-8"))
    gate = json.loads((DIRECTORIES["logs"] / "engineering_release_gate.json").read_text(encoding="utf-8"))
    assert qa["validation_status"] == "PASS"
    assert gate["status"] == "PASS"
    assert gate["candidate_state"] == "ENGINEERING_RELEASE_CANDIDATE"


@pytest.mark.skipif(not _delivery_ready(), reason="The final delivery ZIP is generated by the full rebuild.")
def test_final_delivery_package_contains_report_manifest_and_no_forbidden_artifacts() -> None:
    package = DIRECTORIES["deliverables"] / f"{PACKAGE_BASENAME}.zip"
    manifest = json.loads((DIRECTORIES["deliverables"] / "FINAL_DELIVERY_PACKAGE_MANIFEST.json").read_text(encoding="utf-8"))
    assert manifest["identifier"] == DELIVERY_IDENTIFIER
    assert manifest["release_status"] == "DELIVERY_PACKAGE_READY"
    assert manifest["zip_verification"]["passed"] is True
    assert package.stat().st_size > 5_000_000
    with zipfile.ZipFile(package) as archive:
        names = set(archive.namelist())
        assert "AquaSkim-Sim_Final_Report.docx" in names
        assert "DELIVERY_MANIFEST.json" in names
        assert "DELIVERY_README.md" in names
        assert "outputs/logs/final_word_report_qa.json" in names
        assert "outputs/logs/engineering_release_gate.json" in names
        assert not any("backup" in name.lower() for name in names)
        assert not any(name.endswith(".pyc") or "__pycache__" in name for name in names)
        assert not any("patch_notes" in name or "patch_history" in name or "INCIDENTS" in name for name in names)


def test_required_reproduction_scripts_are_present_and_nonempty() -> None:
    from aquaskim.delivery_package import REQUIRED_REPRODUCTION_SCRIPTS
    from aquaskim.paths import PROJECT_ROOT

    missing_or_empty = [
        relative
        for relative in REQUIRED_REPRODUCTION_SCRIPTS
        if not (PROJECT_ROOT / relative).exists() or (PROJECT_ROOT / relative).stat().st_size <= 0
    ]
    assert missing_or_empty == []
    rows = preflight_reproduction_scripts()
    assert len(rows) == len(REQUIRED_REPRODUCTION_SCRIPTS)
    assert all(row["exists"] and row["size_bytes"] > 0 for row in rows)
