from __future__ import annotations

import json
import zipfile

import pytest
from docx import Document

from aquaskim.final_word_report import MIN_REPORT_TABLES, _metadata
from aquaskim.paths import DIRECTORIES




def _word_report_ready() -> bool:
    return (
        (DIRECTORIES["reports"] / "AquaSkim-Sim_Final_Report.docx").exists()
        and (DIRECTORIES["reports"] / "phase10_report_build_manifest.json").exists()
        and (DIRECTORIES["logs"] / "final_word_report_qa.json").exists()
    )


def _word_manifest_ready() -> bool:
    return (
        (DIRECTORIES["reports"] / "phase10_report_build_manifest.json").exists()
        and (DIRECTORIES["logs"] / "final_word_report_qa.json").exists()
    )

def _gate_json_path():
    return DIRECTORIES["logs"] / "engineering_release_gate.json"


def _gate_passed() -> bool:
    path = _gate_json_path()
    if not path.exists():
        return False
    try:
        gate = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return False
    return gate.get("status") == "PASS" and gate.get("candidate_state") == "ENGINEERING_RELEASE_CANDIDATE"


def test_report_metadata_is_project_local_and_complete() -> None:
    metadata = _metadata()
    assert metadata["student_name"]
    assert metadata["student_id"]
    assert metadata["course"] == "ربات‌های متحرک خودگردان"


@pytest.mark.skipif(not _gate_passed(), reason="Engineering Release Gate PASS output is required for Word QA.")
def test_release_candidate_remains_word_only_precondition() -> None:
    gate = json.loads(_gate_json_path().read_text(encoding="utf-8"))
    assert gate["status"] == "PASS"
    assert gate["candidate_state"] == "ENGINEERING_RELEASE_CANDIDATE"
    assert gate["final_release_enabled"] is False


@pytest.mark.skipif(not _word_report_ready(), reason="Final Word report and manifest are generated together by Patch 10.18.")
def test_generated_word_report_is_structurally_traceable() -> None:
    report = DIRECTORIES["reports"] / "AquaSkim-Sim_Final_Report.docx"
    assert report.exists()
    assert report.stat().st_size > 500_000
    with zipfile.ZipFile(report) as archive:
        names = archive.namelist()
        assert "word/document.xml" in names
        assert len([name for name in names if name.startswith("word/media/")]) >= 25
    doc = Document(report)
    assert len(doc.tables) >= MIN_REPORT_TABLES
    text = "\n".join(p.text for p in doc.paragraphs)
    assert "AquaSkim" in text
    assert "hydrostatics" in text.lower()
    assert "model boundary" in text.lower()


@pytest.mark.skipif(not _word_manifest_ready(), reason="Final Word manifest is generated by Patch 10.18.")
def test_final_word_manifest_records_sources_derivatives_and_no_delivery_zip() -> None:
    manifest = json.loads((DIRECTORIES["reports"] / "phase10_report_build_manifest.json").read_text(encoding="utf-8"))
    qa = json.loads((DIRECTORIES["logs"] / "final_word_report_qa.json").read_text(encoding="utf-8"))
    assert manifest["report_validation"]["validation_status"] == "PASS"
    assert qa["validation_status"] == "PASS"
    assert len(manifest["embedded_figures"]) >= 25
    assert len(manifest["report_image_derivatives"]) >= 25
    assert not list(DIRECTORIES["deliverables"].glob("*.zip"))
