from __future__ import annotations

import json
from pathlib import Path
import zipfile

import pytest
from docx import Document

from aquaskim.paths import DIRECTORIES, PROJECT_ROOT
from aquaskim.phase10 import _metadata


REPORT = DIRECTORIES["reports"] / "AquaSkim-Sim_Final_Report.docx"
MANIFEST = DIRECTORIES["reports"] / "phase10_report_build_manifest.json"


def test_cover_metadata_schema_is_available() -> None:
    metadata = _metadata()
    assert set(metadata) == {
        "student_name", "student_id", "course", "instructor", "institution", "semester"
    }
    assert metadata["course"]


@pytest.mark.skipif(not REPORT.exists(), reason="Final report is generated by Phase 10 before its recorded pytest step.")
def test_generated_report_is_a_traceable_docx() -> None:
    assert REPORT.stat().st_size > 100_000
    with zipfile.ZipFile(REPORT) as archive:
        names = archive.namelist()
        assert "word/document.xml" in names
        assert len([name for name in names if name.startswith("word/media/")]) >= 20
    document = Document(REPORT)
    text = "\n".join(paragraph.text for paragraph in document.paragraphs)
    assert "AquaSkim" in text
    assert "hydrostatics" in text.lower()


@pytest.mark.skipif(not MANIFEST.exists(), reason="Final report manifest is generated by Phase 10.")
def test_report_manifest_hashes_sources_and_figures() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    assert manifest["report_validation"]["validation_status"] == "PASS"
    assert len(manifest["source_files"]) >= 9
    assert len(manifest["embedded_figures"]) >= 25
    assert len(manifest["report_image_derivatives"]) >= 25


def test_cover_metadata_allows_omitted_optional_semester_without_personal_data() -> None:
    metadata = _metadata()
    # Patch 10.10 keeps the delivery stage disabled. Local cover metadata may
    # therefore remain blank; schema validity must not require personal data.
    assert "semester" in metadata
    assert metadata["semester"] == ""
    assert isinstance(metadata["student_name"], str)
