from __future__ import annotations

"""Public-repository hygiene checks for AquaSkim-Sim."""

from dataclasses import dataclass
import json
from pathlib import Path
import subprocess

from aquaskim.paths import PROJECT_ROOT

FORBIDDEN_ROOT_FILES = {"cd", "dir", "powershell", "tar", "type", "src_placeholder", "run_all.sh"}
FORBIDDEN_LOCAL_FILES = {
    "config/report_metadata.json",
    "config/user_profile.yaml",
}
FORBIDDEN_TRACKED_PREFIXES = (
    "patch_notes/",
    "docs/patch_history/",
    "docs/INCIDENTS/",
    "src/aquaskim_sim.egg-info/",
)
FORBIDDEN_TRACKED_NAMES = {
    "run_patch_",
}
REQUIRED_PUBLIC_FILES = {
    "README.md",
    "README_FA.md",
    "LICENSE",
    "CITATION.cff",
    "environment.yml",
    "pyproject.toml",
    "scripts/run_from_zero_to_delivery.bat",
    "scripts/run_from_zero_to_delivery.sh",
    "scripts/run_tests.bat",
    "src/aquaskim/rebuild_from_zero.py",
    "config/report_metadata.template.json",
    "docs/MODELING_AND_VALIDATION.md",
    ".github/workflows/ci.yml",
}
REQUIRED_README_PHRASES = {
    "scripts\\run_from_zero_to_delivery.bat",
    "AquaSkim-Sim_Final_Delivery_v1.6.21.zip",
    "sea-trial certification",
    "SHA-256",
}
ALLOWED_GENERATED_TRACKED_FILES = {
    "outputs/.gitkeep",
    "records/.gitkeep",
}


@dataclass(frozen=True)
class ReadinessCheck:
    name: str
    passed: bool
    detail: str


def _exists(relative: str) -> bool:
    return (PROJECT_ROOT / relative).exists()


def _git_ls_files(*paths: str) -> list[str]:
    try:
        completed = subprocess.run(
            ["git", "ls-files", *paths],
            cwd=PROJECT_ROOT,
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except FileNotFoundError:
        return []
    if completed.returncode != 0:
        return []
    return sorted(
        line.strip().replace("\\", "/")
        for line in completed.stdout.splitlines()
        if line.strip()
    )


def _tracked_generated_artifacts() -> list[str]:
    tracked = _git_ls_files("outputs", "records")
    return sorted(path for path in tracked if path not in ALLOWED_GENERATED_TRACKED_FILES)


def _forbidden_tracked_artifacts() -> list[str]:
    tracked = _git_ls_files()
    hits: list[str] = []
    for path in tracked:
        name = Path(path).name
        if path.startswith(FORBIDDEN_TRACKED_PREFIXES):
            hits.append(path)
        elif any(name.startswith(prefix) for prefix in FORBIDDEN_TRACKED_NAMES):
            hits.append(path)
    return sorted(hits)


def _public_text_leaks() -> list[str]:
    roots = [PROJECT_ROOT / "README.md", PROJECT_ROOT / "README_FA.md"]
    roots.extend((PROJECT_ROOT / "docs").glob("*.md"))
    roots.extend((PROJECT_ROOT / "scripts").glob("*"))
    forbidden_tokens = ("chatgpt", "openai", "generated by ai", "ai-generated")
    hits: list[str] = []
    for path in roots:
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8").lower()
        except UnicodeDecodeError:
            continue
        if any(token in text for token in forbidden_tokens):
            hits.append(path.relative_to(PROJECT_ROOT).as_posix())
    return sorted(set(hits))


def run_github_readiness_checks() -> list[ReadinessCheck]:
    checks: list[ReadinessCheck] = []

    missing = sorted(path for path in REQUIRED_PUBLIC_FILES if not _exists(path))
    checks.append(ReadinessCheck("required_public_files", not missing, json.dumps(missing, ensure_ascii=False)))

    root_hits = sorted(
        path.name
        for path in PROJECT_ROOT.iterdir()
        if path.is_file() and path.name in FORBIDDEN_ROOT_FILES
    )
    checks.append(
        ReadinessCheck(
            "no_accidental_root_command_files",
            not root_hits,
            json.dumps(root_hits, ensure_ascii=False),
        )
    )

    local_hits = sorted(path for path in FORBIDDEN_LOCAL_FILES if _exists(path))
    checks.append(ReadinessCheck("no_local_metadata_files", not local_hits, json.dumps(local_hits, ensure_ascii=False)))

    generated_hits = _tracked_generated_artifacts()
    checks.append(
        ReadinessCheck(
            "no_generated_outputs_committed",
            not generated_hits,
            json.dumps(generated_hits, ensure_ascii=False),
        )
    )

    process_hits = _forbidden_tracked_artifacts()
    checks.append(
        ReadinessCheck(
            "no_internal_process_artifacts",
            not process_hits,
            json.dumps(process_hits, ensure_ascii=False),
        )
    )

    disclosure_hits = _public_text_leaks()
    checks.append(
        ReadinessCheck(
            "no_ai_disclosure_markers_in_public_docs",
            not disclosure_hits,
            json.dumps(disclosure_hits, ensure_ascii=False),
        )
    )

    readme = PROJECT_ROOT / "README.md"
    text = readme.read_text(encoding="utf-8") if readme.exists() else ""
    missing_phrases = sorted(phrase for phrase in REQUIRED_README_PHRASES if phrase not in text)
    checks.append(
        ReadinessCheck(
            "readme_documents_rebuild_and_scope",
            not missing_phrases,
            json.dumps(missing_phrases, ensure_ascii=False),
        )
    )

    gitignore = PROJECT_ROOT / ".gitignore"
    gitignore_text = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    required_ignore_tokens = [
        "outputs/**",
        "records/**",
        "*.egg-info/",
        "config/report_metadata.json",
        "config/user_profile.yaml",
    ]
    missing_ignore_tokens = sorted(token for token in required_ignore_tokens if token not in gitignore_text)
    checks.append(
        ReadinessCheck(
            "gitignore_protects_generated_and_local_files",
            not missing_ignore_tokens,
            json.dumps(missing_ignore_tokens, ensure_ascii=False),
        )
    )

    return checks


def main() -> int:
    checks = run_github_readiness_checks()
    print("=" * 72)
    print("AquaSkim-Sim | GitHub publication readiness")
    print("=" * 72)
    for check in checks:
        state = "OK" if check.passed else "FAIL"
        print(f"[{state}] {check.name}: {check.detail}")
    passed = all(check.passed for check in checks)
    print(f"Status: {'PASS' if passed else 'FAIL'}")
    print("=" * 72)
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
