"""Presentation-grade curation and QA for existing AquaSkim reference evidence.

This module deliberately does not run a new mission or manufacture evidence. It
selects explicit source artifacts generated by the fixed reference protocols,
checks their readibility and claim classification, and copies them to a clearly
separated curated-evidence folder for later report work.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any
import hashlib
import json
import re
import shutil
import subprocess
import xml.etree.ElementTree as ET

import yaml
from PIL import Image, ImageDraw, ImageOps

from aquaskim.reference_design import project_root

VALID_CLAIM_CLASSES = {"validated", "boundary", "controlled_failure", "mixed"}
FORBIDDEN_LEGACY_TOKENS = ("phase08", "phase09", "phase_08", "phase_09", "mission_topdown", "mission_vehicle", "mission_force_vectors")
VISIBLE_LABEL_PATTERN = re.compile(r"\b(?:phase|patch)\b", re.IGNORECASE)


@dataclass(frozen=True)
class CuratedAsset:
    identifier: str
    asset_type: str
    title: str
    claim_class: str
    priority: int
    source: Path
    curated: Path

    def as_dict(self) -> dict[str, Any]:
        return {
            "id": self.identifier,
            "asset_type": self.asset_type,
            "title": self.title,
            "claim_class": self.claim_class,
            "priority": self.priority,
            "source": _relative(self.source),
            "curated": _relative(self.curated),
        }


def _relative(path: Path) -> str:
    root = project_root().resolve()
    try:
        return path.resolve().relative_to(root).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_presentation_curation(path: Path | None = None) -> dict[str, Any]:
    source = path or project_root() / "config" / "reference_presentation_curation.yaml"
    data = yaml.safe_load(source.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Presentation curation configuration must be a mapping.")
    validate_curation_spec(data)
    return data


def validate_curation_spec(spec: dict[str, Any]) -> None:
    if not str(spec.get("identifier", "")).startswith("AQUASKIM-REF-PRESENT-"):
        raise ValueError("Curation identifier is missing or invalid.")
    for collection_name, fields in (("figures", ("source",)), ("media", ("gif", "mp4"))):
        collection = spec.get(collection_name)
        if not isinstance(collection, list) or not collection:
            raise ValueError(f"{collection_name} must contain at least one selected asset.")
        seen: set[str] = set()
        for entry in collection:
            if not isinstance(entry, dict):
                raise ValueError(f"{collection_name} entries must be mappings.")
            identifier = str(entry.get("id", "")).strip()
            if not identifier or identifier in seen:
                raise ValueError(f"{collection_name} contains an invalid or duplicate id: {identifier!r}")
            seen.add(identifier)
            claim = str(entry.get("claim_class", ""))
            if claim not in VALID_CLAIM_CLASSES:
                raise ValueError(f"{identifier} has an unsupported claim class: {claim!r}")
            title = str(entry.get("title", ""))
            if not title or VISIBLE_LABEL_PATTERN.search(title):
                raise ValueError(f"{identifier} has an unsuitable presentation title.")
            for field in fields:
                relative = str(entry.get(field, ""))
                lower = relative.lower()
                if not relative.startswith("outputs/") or not lower.endswith((".png", ".gif", ".mp4")):
                    raise ValueError(f"{identifier} has an invalid source path for {field}.")
                if not lower.startswith("outputs/figures/reference_") and not lower.startswith("outputs/animations/reference_") and not lower.startswith("outputs/videos/reference_"):
                    raise ValueError(f"{identifier} does not point to fixed reference evidence.")
                if any(token in lower for token in FORBIDDEN_LEGACY_TOKENS):
                    raise ValueError(f"{identifier} points to a legacy or uncurated animation.")
    media_classes = {str(entry["claim_class"]) for entry in spec["media"]}
    if not {"boundary", "controlled_failure"}.issubset(media_classes):
        raise ValueError("Curation must keep labelled boundary and controlled-failure evidence.")


def _svg_visible_text(svg_path: Path) -> str:
    try:
        root = ET.parse(svg_path).getroot()
    except (ET.ParseError, OSError) as exc:
        raise ValueError(f"Could not parse SVG companion {svg_path.name}: {exc}") from exc
    values: list[str] = []
    for element in root.iter():
        if element.tag.rsplit("}", 1)[-1] == "text":
            values.append("".join(element.itertext()))
    return " ".join(values)


def _inspect_figure(source: Path, quality: dict[str, Any]) -> dict[str, Any]:
    if not source.exists():
        raise FileNotFoundError(f"Selected figure is missing: {_relative(source)}")
    with Image.open(source) as image:
        width, height = image.size
    svg = source.with_suffix(".svg")
    visible_text = _svg_visible_text(svg) if svg.exists() else ""
    forbidden_visible_terms = sorted(set(VISIBLE_LABEL_PATTERN.findall(visible_text)))
    result = {
        "exists": True,
        "size_bytes": source.stat().st_size,
        "sha256": _sha256(source),
        "width_px": width,
        "height_px": height,
        "min_width_ok": width >= int(quality["min_width_px"]),
        "min_height_ok": height >= int(quality["min_height_px"]),
        "svg_companion_exists": svg.exists(),
        "visible_phase_or_patch_label": bool(forbidden_visible_terms),
    }
    if not result["min_width_ok"] or not result["min_height_ok"]:
        raise ValueError(f"Figure below presentation quality threshold: {_relative(source)}")
    if result["visible_phase_or_patch_label"]:
        raise ValueError(f"Visible Phase/Patch label found in selected SVG: {_relative(svg)}")
    return result


def _inspect_gif(source: Path, quality: dict[str, Any]) -> dict[str, Any]:
    if not source.exists():
        raise FileNotFoundError(f"Selected GIF is missing: {_relative(source)}")
    with Image.open(source) as image:
        frame_count = int(getattr(image, "n_frames", 1))
        width, height = image.size
        durations: list[int] = []
        for frame_index in range(frame_count):
            image.seek(frame_index)
            durations.append(int(image.info.get("duration", 0)))
    duration_s = sum(durations) / 1000.0
    result = {
        "exists": True,
        "size_bytes": source.stat().st_size,
        "sha256": _sha256(source),
        "frames": frame_count,
        "duration_s": round(duration_s, 3),
        "width_px": width,
        "height_px": height,
        "frame_count_ok": frame_count >= int(quality["min_gif_frames"]),
        "duration_ok": duration_s >= float(quality["min_gif_duration_s"]),
        "resolution_ok": width >= int(quality["min_gif_width_px"]) and height >= int(quality["min_gif_height_px"]),
    }
    if not all((result["frame_count_ok"], result["duration_ok"], result["resolution_ok"])):
        raise ValueError(f"GIF presentation QA failed: {_relative(source)}")
    return result


def _inspect_mp4(source: Path, quality: dict[str, Any]) -> dict[str, Any]:
    if not source.exists():
        raise FileNotFoundError(f"Selected MP4 is missing: {_relative(source)}")
    completed = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration:stream=width,height", "-of", "json", str(source)],
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        raise ValueError(f"ffprobe could not read {_relative(source)}: {completed.stderr.strip()}")
    try:
        payload = json.loads(completed.stdout)
        stream = next(item for item in payload.get("streams", []) if item.get("width") and item.get("height"))
        width, height = int(stream["width"]), int(stream["height"])
        duration_s = float(payload.get("format", {}).get("duration", 0.0))
    except (KeyError, StopIteration, ValueError, TypeError, json.JSONDecodeError) as exc:
        raise ValueError(f"ffprobe returned incomplete metadata for {_relative(source)}") from exc
    result = {
        "exists": True,
        "size_bytes": source.stat().st_size,
        "sha256": _sha256(source),
        "readable": True,
        "width_px": width,
        "height_px": height,
        "duration_s": round(duration_s, 3),
        "duration_ok": duration_s >= float(quality["min_mp4_duration_s"]),
        "resolution_ok": width >= int(quality["min_mp4_width_px"]) and height >= int(quality["min_mp4_height_px"]),
    }
    if not result["duration_ok"] or not result["resolution_ok"]:
        raise ValueError(f"MP4 presentation QA failed: {_relative(source)}")
    return result


def _curated_root() -> Path:
    return project_root() / "outputs" / "presentation_evidence"


def _make_figure_contact_sheet(items: list[CuratedAsset], output: Path) -> None:
    columns, thumb_w, thumb_h, label_h = 3, 420, 252, 64
    margin, header_h = 24, 52
    rows = (len(items) + columns - 1) // columns
    canvas = Image.new("RGB", (margin * 2 + columns * thumb_w, header_h + margin + rows * (thumb_h + label_h + margin)), "white")
    draw = ImageDraw.Draw(canvas)
    draw.text((margin, 16), "Curated engineering figures - source-qualified reference evidence", fill=(18, 48, 71))
    for index, item in enumerate(items):
        row, col = divmod(index, columns)
        x = margin + col * thumb_w
        y = header_h + row * (thumb_h + label_h + margin)
        with Image.open(item.curated) as source:
            image = ImageOps.contain(source.convert("RGB"), (thumb_w - 10, thumb_h - 10))
        canvas.paste(image, (x + (thumb_w - image.width) // 2, y + (thumb_h - image.height) // 2))
        draw.rectangle((x, y, x + thumb_w - 1, y + thumb_h - 1), outline=(203, 215, 224), width=1)
        label = f"{index + 1:02d}. {item.title} [{item.claim_class}]"
        draw.text((x + 4, y + thumb_h + 8), label, fill=(57, 67, 77))
    output.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output)


def _write_report(path: Path, spec: dict[str, Any], figures: list[dict[str, Any]], media: list[dict[str, Any]], overview: Path, figure_sheet: Path, media_sheet: Path) -> None:
    lines = [
        "# Curated Reference Evidence for Presentation",
        "",
        "## Scope",
        "This is a curation and visual-QA record for existing fixed-reference evidence. It does not create a Word report, delivery ZIP or release declaration.",
        "",
        "## Selection policy",
        "- Only `reference_*` artifacts are admitted.",
        "- Legacy media and historical quota-based paths are excluded.",
        "- Boundary and controlled-failure material remains explicitly labelled as limitations.",
        "- Selected SVG text is checked for visible `Phase` or `Patch` labels.",
        "",
        "## Curated figures",
        "| ID | Claim class | Presentation title | Source |",
        "|---|---|---|---|",
    ]
    for row in figures:
        lines.append(f"| {row['id']} | {row['claim_class']} | {row['title']} | `{row['source']}` |")
    lines.extend(["", "## Curated media", "| ID | Claim class | Presentation title | GIF | MP4 |", "|---|---|---|---|---|"])
    for row in media:
        lines.append(f"| {row['id']} | {row['claim_class']} | {row['title']} | `{row['gif']['source']}` | `{row['mp4']['source']}` |")
    lines.extend([
        "",
        "## Visual QA",
        f"- Figures selected: `{len(figures)}`.",
        f"- GIF / MP4 pairs selected: `{len(media)} / {len(media)}`.",
        "- All selected figures and media met the configured readability, duration and resolution thresholds.",
        f"- Figure contact sheet: `{_relative(figure_sheet)}`.",
        f"- Media contact sheet: `{_relative(media_sheet)}`.",
        f"- Presentation overview: `{_relative(overview)}`.",
        "",
        "## Model boundary",
        "Curation does not expand the model boundary. Visual evidence remains numerical output of the documented low-speed 3-DOF sheltered-basin model; it is not sea-trial footage, current estimation, wave-response evidence or certification.",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _overview_image(output: Path, figures: list[dict[str, Any]], media: list[dict[str, Any]]) -> None:
    from matplotlib import pyplot as plt
    from aquaskim.visual_quality import PALETTE, add_figure_header, apply_engineering_style, style_axis
    apply_engineering_style()
    fig, axes = plt.subplots(1, 2, figsize=(14, 7.8), gridspec_kw={"width_ratios": [1.05, 1.35]})
    fig.subplots_adjust(left=0.085, right=0.965, top=0.84, bottom=0.18, wspace=0.20)
    add_figure_header(fig, "Curated engineering evidence", "Reference-only selection, explicit limitation labels and visual QA", title_y=0.965, subtitle_y=0.928)
    classes = ["validated", "boundary", "controlled_failure", "mixed"]
    labels = ["Validated", "Boundary", "Controlled failure", "Mixed"]
    colors = [PALETTE["green"], PALETTE["orange"], PALETTE["gray_dark"], PALETTE["blue"]]
    counts = [sum(row["claim_class"] == cls for row in figures) for cls in classes]
    axes[0].bar(labels, counts, color=colors)
    axes[0].set_ylabel("Selected figures")
    axes[0].set_ylim(0, max(counts) + 2)
    axes[0].tick_params(axis="x", labelrotation=12)
    style_axis(axes[0])
    for index, value in enumerate(counts):
        axes[0].text(index, value + 0.15, str(value), ha="center", color=PALETTE["gray_dark"], fontweight="bold")
    media_counts = [sum(row["claim_class"] == cls for row in media) for cls in classes]
    axes[1].barh(labels, media_counts, color=colors)
    axes[1].set_xlabel("Selected GIF / MP4 pairs", labelpad=8)
    axes[1].set_xlim(0, max(media_counts) + 2)
    style_axis(axes[1])
    for index, value in enumerate(media_counts):
        axes[1].text(value + 0.1, index, str(value), va="center", color=PALETTE["gray_dark"], fontweight="bold")
    fig.text(0.055, 0.055, "Validated items may support operating claims within the stated model boundary. Boundary and controlled-failure items are retained only to communicate limitations.", color=PALETTE["gray_dark"], fontsize=8.8)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=240)
    fig.savefig(output.with_suffix(".svg"))
    plt.close(fig)


def _image_quality(path: Path, *, min_width: int, min_height: int) -> dict[str, Any]:
    with Image.open(path) as image:
        width, height = image.size
    result = {
        "path": _relative(path),
        "exists": path.exists(),
        "size_bytes": path.stat().st_size,
        "width_px": width,
        "height_px": height,
        "resolution_ok": width >= min_width and height >= min_height,
    }
    if not result["resolution_ok"]:
        raise ValueError(f"Curated QA image below threshold: {_relative(path)}")
    return result

def curate_presentation_evidence() -> dict[str, Any]:
    spec = load_presentation_curation()
    root = project_root()
    curated_root = _curated_root()
    figure_dir = curated_root / "figures"
    animation_dir = curated_root / "animations"
    video_dir = curated_root / "videos"
    for directory in (figure_dir, animation_dir, video_dir):
        directory.mkdir(parents=True, exist_ok=True)

    selected_figures: list[CuratedAsset] = []
    figure_manifest: list[dict[str, Any]] = []
    for entry in spec["figures"]:
        source = root / entry["source"]
        curated = figure_dir / source.name
        quality = _inspect_figure(source, spec["figure_quality"])
        shutil.copy2(source, curated)
        asset = CuratedAsset(str(entry["id"]), "figure", str(entry["title"]), str(entry["claim_class"]), int(entry["report_priority"]), source, curated)
        selected_figures.append(asset)
        figure_manifest.append({**asset.as_dict(), "quality": quality, "curated_sha256": _sha256(curated)})

    selected_media: list[tuple[CuratedAsset, CuratedAsset]] = []
    media_manifest: list[dict[str, Any]] = []
    for entry in spec["media"]:
        gif_source = root / entry["gif"]
        mp4_source = root / entry["mp4"]
        gif_curated, mp4_curated = animation_dir / gif_source.name, video_dir / mp4_source.name
        gif_quality = _inspect_gif(gif_source, spec["media_quality"])
        mp4_quality = _inspect_mp4(mp4_source, spec["media_quality"])
        shutil.copy2(gif_source, gif_curated)
        shutil.copy2(mp4_source, mp4_curated)
        gif_asset = CuratedAsset(str(entry["id"]), "gif", str(entry["title"]), str(entry["claim_class"]), int(entry["presentation_priority"]), gif_source, gif_curated)
        mp4_asset = CuratedAsset(str(entry["id"]), "mp4", str(entry["title"]), str(entry["claim_class"]), int(entry["presentation_priority"]), mp4_source, mp4_curated)
        selected_media.append((gif_asset, mp4_asset))
        media_manifest.append({"id": str(entry["id"]), "title": str(entry["title"]), "claim_class": str(entry["claim_class"]), "priority": int(entry["presentation_priority"]), "gif": {**gif_asset.as_dict(), "quality": gif_quality, "curated_sha256": _sha256(gif_curated)}, "mp4": {**mp4_asset.as_dict(), "quality": mp4_quality, "curated_sha256": _sha256(mp4_curated)}})

    figure_sheet = curated_root / "reference_presentation_figure_contact_sheet.png"
    media_sheet = curated_root / "reference_presentation_media_contact_sheet.png"
    overview = root / "outputs" / "figures" / "reference_presentation_evidence_overview.png"
    _make_figure_contact_sheet(selected_figures, figure_sheet)
    from aquaskim.animation_audit import write_animation_audit_sheet
    write_animation_audit_sheet([pair[0].curated for pair in selected_media], media_sheet)
    _overview_image(overview, figure_manifest, media_manifest)
    overview_quality = _image_quality(overview, min_width=1200, min_height=700)
    figure_sheet_quality = _image_quality(figure_sheet, min_width=1200, min_height=1000)
    media_sheet_quality = _image_quality(media_sheet, min_width=1200, min_height=1000)

    report = root / "outputs" / "reports" / "reference_presentation_curation.md"
    visual_qa = root / "outputs" / "logs" / "reference_presentation_visual_quality_manifest.json"
    inventory = root / "outputs" / "logs" / "reference_presentation_curation_manifest.json"
    _write_report(report, spec, figure_manifest, media_manifest, overview, figure_sheet, media_sheet)
    summary = {
        "identifier": spec["identifier"],
        "status": "PASS",
        "policy": spec["policy"],
        "figure_count": len(figure_manifest),
        "media_pair_count": len(media_manifest),
        "claim_classes": {claim: sum(row["claim_class"] == claim for row in figure_manifest + media_manifest) for claim in sorted(VALID_CLAIM_CLASSES)},
        "figures": figure_manifest,
        "media": media_manifest,
        "figure_contact_sheet": _relative(figure_sheet),
        "media_contact_sheet": _relative(media_sheet),
        "overview": _relative(overview),
        "overview_quality": overview_quality,
        "figure_contact_sheet_quality": figure_sheet_quality,
        "media_contact_sheet_quality": media_sheet_quality,
    }
    visual_summary = {
        "identifier": "AQUASKIM-REF-PRESENT-VIS-01",
        "status": "PASS",
        "selected_figures": len(figure_manifest),
        "selected_gifs": len(media_manifest),
        "selected_mp4s": len(media_manifest),
        "all_figure_quality_checks_ok": True,
        "all_gif_quality_checks_ok": True,
        "all_mp4_quality_checks_ok": True,
        "visible_phase_or_patch_labels": False,
        "legacy_assets_selected": False,
        "overview_quality": overview_quality,
        "figure_contact_sheet_quality": figure_sheet_quality,
        "media_contact_sheet_quality": media_sheet_quality,
        "figure_contact_sheet": _relative(figure_sheet),
        "media_contact_sheet": _relative(media_sheet),
    }
    inventory.parent.mkdir(parents=True, exist_ok=True)
    inventory.write_text(json.dumps(summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    visual_qa.write_text(json.dumps(visual_summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return {
        "report": report,
        "inventory": inventory,
        "visual_qa": visual_qa,
        "overview": overview,
        "figure_contact_sheet": figure_sheet,
        "media_contact_sheet": media_sheet,
        "curated_root": curated_root,
        "figure_count": len(figure_manifest),
        "media_pair_count": len(media_manifest),
    }
